# -*- coding: utf-8 -*-
"""Medical_chatbot_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IGkY8KjAyZniH5ndASuiayW055eMJREh
"""

from openai import OpenAI

# Initialize OpenAI client
client = OpenAI(api_key="")


SYSTEM_PROMPT = """
You are a Medical AI Chatbot.

Purpose:
- Provide GENERAL medical information and educational guidance.
- Users may ask about ANY medical ailment or health-related topic.
- Do NOT provide diagnosis, prescriptions, or personalized treatment plans.

Rules:
- Always clarify that responses are general medical information only.
- Clearly state that individual health conditions differ.
- Encourage users to consult a qualified medical practitioner for
  diagnosis, treatment, or medical emergencies.
- Avoid definitive medical claims.

Tone:
- Professional, clear, and supportive.
"""


DISCLAIMER = """
⚠️ MEDICAL DISCLAIMER

This Medical AI Chatbot provides GENERAL medical information only.
It does NOT replace professional medical advice, diagnosis, or treatment.

Health conditions vary from person to person.
Always consult a qualified medical practitioner or registered doctor
for medical concerns, diagnosis, or treatment decisions.
"""


def medical_chatbot():
    print("=" * 70)
    print("🩺 MEDICAL AI CHATBOT")
    print("=" * 70)
    print(
        "You may ask GENERAL questions about medical advice for ANY ailment.\n"
        "This chatbot does NOT diagnose or prescribe medicines.\n"
    )
    print(DISCLAIMER)
    print("Type 'exit' to quit.\n")

    while True:
        user_input = input("User: ").strip()

        if user_input.lower() in ["exit", "quit", "bye"]:
            print("\nChatbot: Take care of your health and consult a qualified doctor when needed.")
            break

        try:
            response = client.responses.create(
                model="gpt-5.2",
                input=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": user_input}
                ]
            )

            chatbot_reply = response.output_text

            print("\nChatbot:")
            print(chatbot_reply)
            print("\n" + DISCLAIMER + "\n")

        except Exception as e:
            print("⚠️ Error connecting to the medical AI service.")
            print("Details:", str(e))


if __name__ == "__main__":
    medical_chatbot()