# -*- coding: utf-8 -*-
"""streamlit_medical-chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/yogenkaskhedikar/26b82c0b7ff718c3121428fe7f2071ff/streamlit_medical-chatbot.ipynb
"""

import streamlit as st
from openai import OpenAI

# ----------------------------
# OpenAI Client Initialization
# ----------------------------
client = OpenAI(api_key=st.secrets.get("OPEN_AI_KEY", ""))

# ----------------------------
# System Prompt
# ----------------------------
SYSTEM_PROMPT = """
You are a Medical AI Chatbot.

Purpose:
- Provide GENERAL medical information for ANY medical ailment.
- Educational and informational use only.

Rules:
- Do NOT diagnose medical conditions.
- Do NOT prescribe medicines or treatments.
- Always clarify that advice is general in nature.
- State that individual health conditions vary.
- Encourage consulting a qualified medical practitioner
  for diagnosis, treatment, or emergencies.

Tone:
- Professional, clear, calm, and supportive.
"""

DISCLAIMER = """
⚠️ **Medical Disclaimer**

This chatbot provides **general medical information only**.
It does **not** replace professional medical advice, diagnosis, or treatment.

Health conditions vary from individual to individual.
Always consult a **qualified medical practitioner or registered doctor**
for medical concerns, diagnosis, treatment, or emergencies.
"""

# ----------------------------
# Streamlit Page Config
# ----------------------------
st.set_page_config(
    page_title="Medical AI Chatbot",
    page_icon="🩺",
    layout="centered"
)

# ----------------------------
# UI Header
# ----------------------------
st.title("🩺 Medical AI Chatbot")
st.subheader("General Medical Information Assistant")

st.info(
    "Ask **general medical questions** about **any ailment or health condition**.\n\n"
    "⚠️ This chatbot does NOT diagnose diseases or prescribe medicines."
)

st.markdown(DISCLAIMER)

# ----------------------------
# Chat History
# ----------------------------
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display previous messages
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# ----------------------------
# User Input
# ----------------------------
user_input = st.chat_input("Ask a general medical question...")

if user_input:
    # Show user message
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

    try:
        # Call OpenAI
        response = client.responses.create(
            model="gpt-5.2",
            input=[
                {"role": "system", "content": SYSTEM_PROMPT},
                *st.session_state.messages
            ]
        )

        assistant_reply = response.output_text

        # Store assistant response
        st.session_state.messages.append(
            {"role": "assistant", "content": assistant_reply}
        )

        # Display assistant response
        with st.chat_message("assistant"):
            st.markdown(assistant_reply)
            st.markdown("---")
            st.markdown(DISCLAIMER)

    except Exception as e:
        st.error("⚠️ Unable to connect to the medical AI service.")
        st.write(str(e))
